print(9 == 2)
print(9 != 2)
print(9 > 2)
print(9 < 2)
print(9 <= 2)
print(9 >= 2)
print(7 == 7.0)
print('a' == 'abc')
print('a' != 'abc')
print('a' < 'abc')
print(True < False)
print(True > False)
print(ord('q'))
